server:
  port: 8080
  servlet:
    context-path: /
debug: false
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
spring:
  devtools:
    add-properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.182.13.113:3306/eclp_stock?characterEncoding=utf-8&useSSL=false
    username: eclp
    password: eclp


#mybatis的相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.power.grid.plan
  configuration:
    map-underscore-to-camel-case: true
