server:
  port: 8080
  servlet:
    context-path: /
debug: true
spring:
  mvc:
    static-path-pattern: /**
  devtools:
    add-properties: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3358/power_grid_plan?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 20000
    jedis:
      pool:
        min-idle: 10
        max-idle: 40
        max-active: 20
        max-wait: 10000
      shutdown-timeout: 10000
#mybatis的相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.power.grid.plan.model
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

